### PR TITLE
Fixing Missing and Invalid Variables

### PR DESCRIPTION
**Pull request by wisn**
I've been checked some translation with Dennis.
These are what I got.
If it is any failure please notice me~

### CODE REVIEW

**Comment by ancorgs** [comment]
All the changes look correct to me. But I wonder if this is the correct place to do them. Those .po files are written to the repository by Weblate (https://l10n.opensuse.org/). Not sure if changing them directly here, in the repository will work in the long term.

Let's ask @stanislav-brabec

**Comment by stanislav-brabec** [comment]
It's OK, but a bit dangerous. Even a single edit can break the pull request.

Download po file, edit, upload in Weblate is much safer, as Weblate parses po file. Git does not.

**Comment by wisn** [comment]
I've been created Suse account and I'll puts all of them on the https://l10n.opensuse.org/ soon...
Thank you~

**Comment by stanislav-brabec** [comment]
Well, git still makes sense sometimes. In your case, you probably did a mass fix in the fix in a file manager text editor. In such case, git is really the fastest way to do it. But please ping one of admins first. Such pull requests break pretty quickly, so the review process needs to be fast.

If you make fixes file-by-file, Weblate is a better approach.

**Comment by wisn** [comment]
Alright, maybe in another time I will creates a pull request again.

> But please ping one of admins first. Such pull requests break pretty quickly, so the review process needs to be fast.

Thank you for remind me~

**Pull request merged**
