### PR TITLE
Update rpm-groups.pot

### PR DESCRIPTION
**Pull request by alexminton**
Updated from the latest tumbleweed repo

### CODE REVIEW

**Comment by stanislav-brabec** [comment]
The patch is OK. Do we have some automation for it?

**Comment by alexminton** [comment]
Sure, the actual parser is just a one-liner in Bash, everything else is .po header and syntax. I used this script:
#!/bin/bash
echo "# This file was automatically generated";
echo "msgid \"\""
echo "msgstr \"\""
echo "\"Project-Id-Version: rpm-groups\n\""
echo "\"Report-Msgid-Bugs-To: bugzilla.opensuse.org\n\""
echo "\"POT-Creation-Date: $(date "+%F %R%z")\n\""
echo "\"PO-Revision-Date: $(date "+%F %R%z")\n\""
echo "\"Last-Translator: Automatically generated\n\""
echo "\"Language-Team: openSUSE opensuse-translation@opensuse.org\n\""
echo "\"Language: en\n\""
echo "\"MIME-Version: 1.0\n\""
echo "\"Content-Type: text/plain; charset=UTF-8\n\""
echo "\"Content-Transfer-Encoding: 8bit\n\""
echo "";
curl -s http://downloadcontent.opensuse.org/tumbleweed/repo/oss/suse/setup/descr/packages.gz | gzip -c -d | grep "=Grp: " | sed -e 's/=Grp: //g' | sed -e 's/\//\n/g' | sort -u | while IFS='' read -r line; do
  [ -n "$line" ] && echo "msgid \"$line\"" && echo "msgstr \"\"" && echo ""
done
exit 0

**Comment by stanislav-brabec** [comment]
https://github.com/yast/yast-translations/commit/ef46bfedde22da89c25a196d9c233bac7a719898

**Comment by lnussel** [comment]
note the susetags format will be removed in the near future. we only have repomd then

**Pull request merged**
